#generate settings
name: ~
mode: SR
gpu_ids: [0]

scale: 2
patch_size: 128
train_Y: false

#datasets
datasets:
  train:
    mode: DIV2K
    dataroot_HR: /data/dzc/SISRDataset/DIV2K/DIV2K_train_HR
    dataroot_LR: /data/dzc/SISRDataset/DIV2K/DIV2K_train_LR_bicubic/XN
    filename_path: data/DIV2K_train.txt
    n_workers: 4
    batch_size: 16
    use_flip: true
    use_rot: true
    noise: ~
  val:
    mode: DIV2K
    dataroot_HR: /data/dzc/SISRDataset/DIV2K/DIV2K_train_HR
    dataroot_LR: /data/dzc/SISRDataset/DIV2K/DIV2K_train_LR_bicubic/XN
    filename_path: data/DIV2K_val.txt
    noise: ~

#networks
networks:
  which_model: baseline
  in_channels: 3
  num_fea: 64
  out_channels: 3
  dataparallel: false
      
#path to save
paths:
  experiment_root: ./experiment
  root: ~ # determined by model_name
  epochs: ~ 
  visual: ~ 
  records: ~

#optimizer
solver:
  type: ADAM
  init_type: kaiming
  learning_rate: !!float 1e-3
  weight_decay: 0
  lr_scheme: MultiStepLR
  lr_steps: 
    - 200
    - 400
    - 600
    - 800
  lr_gamma: !!float 0.5
  loss_type: l1
  manual_seed: 0
  num_epochs: 1000
  skip_threshold: 3
  save_vis_step: 100
  val_step: 50
  pretrained: ~

#print
print:
  print_freq: 10
